using DocCoach.Web.Models;

namespace DocCoach.Web.Services.Analyzers;

/// <summary>
/// Context provided to analyzers containing all information needed for analysis.
/// </summary>
public class AnalysisContext
{
    /// <summary>The document being analyzed.</summary>
    public required Document Document { get; init; }
    
    /// <summary>Extracted text content from the document.</summary>
    public required string DocumentText { get; init; }
    
    /// <summary>The guideline set being applied.</summary>
    public required GuidelineSet GuidelineSet { get; init; }
    
    /// <summary>Rules to evaluate (filtered from guideline set).</summary>
    public required IReadOnlyList<Rule> Rules { get; init; }
    
    /// <summary>Cancellation token for long-running operations.</summary>
    public CancellationToken CancellationToken { get; init; }
    
    /// <summary>Optional callback for progress reporting.</summary>
    public Action<AnalysisProgress>? OnProgress { get; init; }
    
    /// <summary>Starting rule index for this analyzer (used for per-rule progress).</summary>
    public int RuleStartIndex { get; init; }
    
    /// <summary>Total rule count across all analyzers (used for per-rule progress).</summary>
    public int TotalRuleCount { get; init; }
}

/// <summary>
/// Result from an individual analyzer.
/// </summary>
public class AnalysisResult
{
    /// <summary>ID of the analyzer that produced this result.</summary>
    public required string AnalyzerId { get; init; }
    
    /// <summary>Display name of the analyzer.</summary>
    public required string AnalyzerName { get; init; }
    
    /// <summary>Whether the analysis completed successfully.</summary>
    public bool Success { get; init; } = true;
    
    /// <summary>Error message if analysis failed.</summary>
    public string? ErrorMessage { get; init; }
    
    /// <summary>Feedback items generated by this analyzer.</summary>
    public List<FeedbackItem> FeedbackItems { get; init; } = new();
    
    /// <summary>Time taken for analysis in milliseconds.</summary>
    public long ProcessingTimeMs { get; init; }
    
    /// <summary>Dimensions covered by this analyzer's results.</summary>
    public IReadOnlySet<ReviewDimension> CoveredDimensions { get; init; } = new HashSet<ReviewDimension>();
    
    /// <summary>Rule types evaluated by this analyzer.</summary>
    public IReadOnlySet<RuleType> EvaluatedRuleTypes { get; init; } = new HashSet<RuleType>();
}

/// <summary>
/// Interface for document analyzers that evaluate specific rules.
/// Each analyzer focuses on particular rule types or dimensions.
/// </summary>
public interface IReviewAnalyzer
{
    /// <summary>Unique identifier for this analyzer.</summary>
    string Id { get; }
    
    /// <summary>Human-readable name for this analyzer.</summary>
    string Name { get; }
    
    /// <summary>Description of what this analyzer evaluates.</summary>
    string Description { get; }
    
    /// <summary>The evaluation mode this analyzer uses.</summary>
    EvaluationMode EvaluationMode { get; }
    
    /// <summary>Review dimensions this analyzer can evaluate.</summary>
    IReadOnlySet<ReviewDimension> SupportedDimensions { get; }
    
    /// <summary>Specific rule types this analyzer can evaluate.</summary>
    IReadOnlySet<RuleType> SupportedRuleTypes { get; }
    
    /// <summary>Priority order for execution (lower = earlier). Default is 100.</summary>
    int Priority { get; }
    
    /// <summary>
    /// Configuration parameters this analyzer accepts.
    /// Used by the admin UI to dynamically render configuration forms.
    /// </summary>
    IReadOnlyList<ConfigParameter> ConfigParameters { get; }
    
    /// <summary>
    /// Determines if this analyzer can handle the given rules.
    /// </summary>
    /// <param name="rules">Rules to evaluate.</param>
    /// <returns>True if this analyzer can evaluate at least one rule.</returns>
    bool CanAnalyze(IEnumerable<Rule> rules);
    
    /// <summary>
    /// Performs analysis on the document and returns feedback items.
    /// </summary>
    /// <param name="context">Analysis context with document and rules.</param>
    /// <returns>Analysis result with feedback items.</returns>
    Task<AnalysisResult> AnalyzeAsync(AnalysisContext context);
}

/// <summary>
/// Base class for analyzers with common functionality.
/// </summary>
public abstract class ReviewAnalyzerBase : IReviewAnalyzer
{
    public abstract string Id { get; }
    public abstract string Name { get; }
    public abstract string Description { get; }
    public abstract EvaluationMode EvaluationMode { get; }
    public abstract IReadOnlySet<ReviewDimension> SupportedDimensions { get; }
    public abstract IReadOnlySet<RuleType> SupportedRuleTypes { get; }
    
    public virtual int Priority => 100;
    
    /// <summary>
    /// Configuration parameters this analyzer accepts.
    /// Override in derived classes to expose configurable options.
    /// </summary>
    public virtual IReadOnlyList<ConfigParameter> ConfigParameters => Array.Empty<ConfigParameter>();
    
    public virtual bool CanAnalyze(IEnumerable<Rule> rules)
    {
        return rules.Any(r => 
            r.IsEnabled && 
            SupportedRuleTypes.Contains(r.RuleType));
    }
    
    public abstract Task<AnalysisResult> AnalyzeAsync(AnalysisContext context);
    
    /// <summary>
    /// Creates a feedback item with common properties set.
    /// </summary>
    protected FeedbackItem CreateFeedbackItem(
        RuleType ruleType,
        FeedbackSeverity severity,
        string title,
        string description,
        string? suggestion = null,
        DocumentLocation? location = null,
        double? confidence = null,
        ReviewDimension? dimension = null,
        string? ruleName = null)
    {
        var effectiveDimension = dimension ?? ReviewDimension.Language;
        
        return new FeedbackItem
        {
            Id = Guid.NewGuid().ToString(),
            Dimension = effectiveDimension,
            RuleType = ruleType,
            RuleName = ruleName,
            Severity = severity,
            Title = title,
            Description = description,
            Suggestion = suggestion,
            Location = location ?? new DocumentLocation(),
            AnalyzerId = Id,
            Confidence = confidence
        };
    }
}
